### ISSUE TITLE
GET /api/appstores/{id}/apps not working

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/DataspaceConnector#128]
After requesting an app from the app store (`POST /api/ids/app`) the requested app is shown on `GET /api/apps`.
But `GET /api/appstores/{id}/apps` returns an empty array.

**Comment by ghost** [comment]
Intermediate result: For me this is working if instead of the `URL` the `UUID` of the previously created AppStore is used at `POST /api/ids/app`.
