### ISSUE TITLE
Docu: Broken link

### ISSUE THREAD

**Issue by ghost** [International-Data-Spaces-Association/DataspaceConnector#248]
Needs to be updated

![image](https://user-images.githubusercontent.com/75306992/168099478-e9b079d8-2654-4945-b32a-fb6412be3276.png)

https://international-data-spaces-association.github.io/DataspaceConnector/Documentation/v6/UsageControl

**Comment by HeLinChooi** [comment]
Found a broken link in https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Configuration.
The text "DAT" in the description of keystore-localhost.p12,
which is https://github.com/International-Data-Spaces-Association/IDS-G/blob/main/core/DAPS/README.md#dynamic-attribute-token-content is not found.
