### ISSUE TITLE
Admin has no access to self-description 

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/DataspaceConnector#30]
This is a more detailed version of https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/671

**Describe the bug**
If I log in as an admin I cannot access the self-description any longer

**To Reproduce**
1. Open Google Chrome
2. Access base URL of DSC (self-description works)
3. Log in via admin credentials (e.g., swagger ui path)
4. Access base URL of DSC --> Not working (type=Forbitten, status=403)
5. Access base URL of DSC via incognito mode works

**Expected behavior**
Admins shall be able to view the self description

**Comment by ghost** [comment]
Will be fixed by replacing `anonymous()` with `permitAll()` for API access control for the above mentioned APIs.
