### ISSUE TITLE
Enhance documentation regarding message flow and message fields

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/DataspaceConnector#317]
The documentation (https://international-data-spaces-association.github.io/DataspaceConnector/Documentation/v6/Messages#messaging-sequence) shall be enhanced to cover all IDS messages from DSC to other components (Connectors, Broker, Clearing House, etc.) with their fields and expected values. The goal is to allow other Connector developers to develop an interoperability to the current defined messages.

- [x] Add all expected incoming message structures and outgoing message structures as examples @tmberthold https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/339 (DSC documentation -> Documentation -> Messages)
- [x] Define which fields are mandatory or non-mandatory in comparison to infomodel's mandatory fields @tmberthold https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/340
- [x] Revise the current message flow diagram with regards to subscriptions and other messages @tmberthold
- [x] Add more information about implementation of IDS Multipart for DSC @tmberthold https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/343

**Comment by ghost** [comment]
The message flow diagram is still up to date.
For some systems, like the DSC GUI, an additional auxiliary API call is added to the first part of the calls. This API-call can, but doesn't need to, be done to dynamically load the policy-JSON-templates from the DSC if they are not stored in the calling application itself. `>>> POST http://connector-container:8080/api/examples/policy`
