### ISSUE TITLE
Appstore Integration not working with latest Portainer version

### ISSUE THREAD

**Issue by hqarawlus** [International-Data-Spaces-Association/DataspaceConnector#35]
**Describe the bug**
The Appstore integration is not working with the latest version of Portainer (v. 2.11.0 at the time of writing). The app metadata is downloaded from the Appstore, but does not start. The integration is fully functional when using Portainer version 2.6.2.  

**To Reproduce**
1. Start latest version of Portainer. 
2. Attempt to download and start an app following [this guide](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/communication/v6/ecosystem/appStore.md).

**Expected behavior**
IDS App starts successfully.

**Screenshots & Logs**
Version 2.11.0
![grafik](https://user-images.githubusercontent.com/78079333/150767236-41270145-eb7d-4b7a-b658-3d2d836c6f3a.png)

Version 2.6.2
![grafik](https://user-images.githubusercontent.com/78079333/150766154-b57892e1-12bb-4a66-941f-3c90f99b431c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: Firefox
 - Version (DSC) [e.g. 22]: 6.6.0-SNAPSHOT

**Additional context**
I started the DSC through docker-compose and set the Portainer application host url in application.properties to "host.docker.internal:9000", so that it can be reachable from the DSC container.

**Comment by ghost** [comment]
Please update to Portainer 2.14.0, tested today - working for me with latest version (DSC 8.0.0 main and Portainer 2.14.0) against FIT AppStore and -Registry. If you have further problems, please feel free to open another Issue/Discussion, so we can look at it again.

Will close this as it works with the latest combination.
