### ISSUE TITLE
Flyway Integration Fails with Spring Boot <2.7.3

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/DataspaceConnector#403]
Version 9 of Flyway removed a field named `ignoreMissingMigrations`.
In Spring Boot 2.7.2 it is still used and leads to an exception. They fixed the issue with version 2.7.3 (released some days ago).
Be aware to use and test Flyway migrations with PostgreSQL only!

**Comment by omarsilva1** [comment]
The released version now uses spring boot 2.7.3
