### ISSUE TITLE
daps.whitelisted.url

### ISSUE THREAD

**Issue by ctoscano-eu** [International-Data-Spaces-Association/DataspaceConnector#406]
On version 7.1.0 I have
    daps.whitelisted.url=https://daps.aisec.fraunhofer.de,https://vcese19.inesctec.pt
(two DAPS)

On version 8.0.0 I have to add a **third entry**
    daps.whitelisted.url=https://daps.aisec.fraunhofer.de,https://vcese19.inesctec.pt,https://vcese19.inesctec.pt/auth
so that the connectors establish the proper IDS communication

The remaining we also have the following variables 
            - 'DAPS_URL=https://vcese19.inesctec.pt'
            - 'DAPS_TOKEN_URL=https://vcese19.inesctec.pt/auth/token'
            - 'DAPS_KEY_URL=https://vcese19.inesctec.pt/auth/jwks.json'
            - 'DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json'

**Comment by SebastianOpriel** [comment]
Looks good so far. Could you please clarify your question or issue?

**Comment by ctoscano-eu** [comment]
The question is why do I need to have two entries for the same DAPS server in the environment variable:
   https://vcese19.inesctec.pt + https://vcese19.inesctec.pt/auth
On the previous version 7.1.0 I had only the first entry , I didn't need to add the second entry.

**Comment by SebastianOpriel** [comment]
For further debug purposes:
Please set `daps.enable.log.jwt=true` in application.properties or `DAPS_ENABLE_LOG_JWT=true` in docker-compose (https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/wiki/09.-Settings:-Connector-Configuration). And in addition log incoming and outgoing IDS messages: https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/ad3743d40f8c475ccfd5c69d6cd558096b90bb90/src/main/resources/application.properties#L96

Please decode your received JWT from DAPS, to be found in the logs after `INFO - Successfully received DAT from DAPS. [response=({"access_token":" {TOKEN}` (e.g. via jwt.io). Please verify, that the `iss` field in the token equals "https://vcese19.inesctec.pt" and your referringConnector equals your Connector base URL. 

I suspect that your DAT "iss" is "https://vcese19.inesctec.pt/auth", which should be "https://vcese19.inesctec.pt"
Your DAPS_KEY_URL seems to be wrong too, as there is no json available. 
Did you have had the DAPS_URL maybe previously as `https://vcese19.inesctec.pt/auth`?

**Comment by ctoscano-eu** [comment]
Dear Sebastien, thank you for the instructions , we will analyse the situation to discover what is going on.

**Comment by ctoscano-eu** [comment]
Problem solved. We defined 'DAPS_URL=https://vcese19.inesctec.pt/auth' so that we can simply add 'https://vcese19.inesctec.pt' to the whitelist.
