### ISSUE TITLE
Email `info@dataspace-connector.de` Does Not Exist

### ISSUE THREAD

**Issue by Krieke** [International-Data-Spaces-Association/DataspaceConnector#561]
**Describe the bug**
main:latest
The email reference `info@dataspace-connector.de` doesn't exist and is used on the pages:
* https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/deployment/update.md
* https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/communication/v6/ecosystem/broker.md
* https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/communication/v6/ecosystem/identityProvider.md
* https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/features.md
* https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/docs/pages/communication.md

**To Reproduce**
1. Send mail to 'info@dataspace-connector.de'
2. See error: One should get an error that the recipient address is rejected due to unknown user.

**Expected behavior**
Existing and active email account

**Desktop (please complete the following information):**
OS: Ubuntu 20.04 LTS
Browser: chrome
Version (DSC): 107.0.5304.110

**Comment by ghost** [comment]
Hello,
please use the following email address in the meantime:
support@sovity.de

We will update the mentioned places in the future, thank you for reporting!

**Comment by omarsilva1** [comment]
Thanks for reporting. I've created a PR that updates to the correct address.
