### ISSUE TITLE
README.md Contains Link to Archived Repository

### ISSUE THREAD

**Issue by Krieke** [International-Data-Spaces-Association/DataspaceConnector#577]
**Describe the bug**
main: latest
In the [README.md](https://github.com/International-Data-Spaces-Association/DataspaceConnector#quick-start) section `quick start` 

1) one can read the following sentence after the word **Note**  For a more detailed or advanced Docker or Kubernetes deployment, as well as a full setup with the Connector and its GUI, see [here]

This link https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/tree/main/dataspace-connector is referring to an archived repository. 

2) one can read the following sentence: The official Docker images of the Dataspace Connector can be found [here]

This link https://github.com/International-Data-Spaces-Association/DataspaceConnector/pkgs/container/dataspace-connector is referring to an archived repository.

**To Reproduce**
1. Press on the links as described above

**Expected behavior**
Documentation references to actively supported and contributed repositories.

**Comment by omarsilva1** [comment]
Hello, thanks for reaching out. 

Regarding the first link: The repository is archived but still contains a setup to start the connector with GUI (one would just have to upate the versions). For another version you could check out the [IDS-Testbed](https://github.com/International-Data-Spaces-Association/IDS-testbed).

Regarding the second: The link to the docker images is correct. The repository is archived but is used for publishing the new images (see images being published 1 day ago) as it was the original repository.
