### ISSUE TITLE
Blocked mirror for repositories when building with Docker

### ISSUE THREAD

**Issue by alzcurda** [International-Data-Spaces-Association/DataspaceConnector#678]
**Describe the bug**
When I try to build a image or use docker-compose I get this error message:

_#15 105.7 Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Blocked mirror for repositories: [eis-public-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public, default, disabled), eis-snapshot-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot, default, releases+snapshots), eis-ids-public (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public, default, releases+snapshots)]_

**To Reproduce**
I get the latest version (8.0.2)
I navigated to DataspaceConnecotr and ran:

_docker build -t dataspaceconnector ._

**Expected behavior**
I expected the connector would work

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/53859497/223483897-168fdb19-a9a8-449b-9742-95280a782adc.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
It works if I launch it using Maven.

**Comment by nuthub** [comment]
Same here on a Linux (GNU Guix) machine!

**Comment by alzcurda** [comment]
I was able to compile using maven version 3.6.
