### ISSUE TITLE
Archive Repository and Documentation

### ISSUE THREAD

**Issue by mhellmeier** [International-Data-Spaces-Association/DataspaceConnector#724]
This repository is a public fork of https://github.com/FraunhoferISST/DataspaceConnector. Since it was last updated in 2022 and the upstream repository is archived in a read-only state, I would also vote to archive this repository.

Further, the documentation is still publicly available via the GitHub IO pages of the IDSA:
https://international-data-spaces-association.github.io/DataspaceConnector/
There isn't a hint that this documentation is outdated. Therefore, it leads to confusion for external people since it can be easily accessed and found via quick web searches. Different concepts and descriptions contrast with other documents, protocols, and specifications of the IDSA, like the dataspace protocol or the latest RAM.

**Comment by ghost** [comment]
We are now adding notes in the various DSC-related repos that these projects are no longer actively maintained and interested new maintainers can contact the International Data Spaces Association, if any are interested.

However, currently this also means, that the projects are not GitHub-technically archived.
